//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказы.
    /// </summary>
    // *** Start programmer edit section *** (Заказы CustomAttributes)

    // *** End programmer edit section *** (Заказы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказыE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "ДатаИВремя as \'Дата и время\'",
            "ТипОплаты as \'Тип оплаты\'",
            "ТипВручения as \'Тип вручения\'",
            "Номера as \'Номера\'",
            "Номера.НомерКомнаты as \'Номер комнаты\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия сотрудника\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.Фамилия as \'Фамилия клиента\'"}, Hidden=new string[] {
            "Номера.НомерКомнаты",
            "Сотрудник.Фамилия",
            "Клиенты.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаказыE", "СоставЗаказа", "СоставЗаказаE", true, "", "Состав заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказыE", "Номера", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКомнаты")]
    [MasterViewDefineAttribute("ЗаказыE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаказыE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаказыL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "ДатаИВремя as \'Дата и время\'",
            "ТипОплаты as \'Тип оплаты\'",
            "ТипВручения as \'Тип вручения\'",
            "Номера.НомерКомнаты as \'Номер комнаты\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Клиенты.Фамилия as \'Фамилия\'"})]
    public class Заказы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private string fДатаИВремя;
        
        private IIS.Serezha.ТипОплаты fТипОплаты;
        
        private IIS.Serezha.ТипВручения fТипВручения;
        
        private IIS.Serezha.Номера fНомера;
        
        private IIS.Serezha.Сотрудник fСотрудник;
        
        private IIS.Serezha.Клиенты fКлиенты;
        
        private IIS.Serezha.DetailArrayOfСоставЗаказа fСоставЗаказа;
        
        // *** Start programmer edit section *** (Заказы CustomMembers)

        // *** End programmer edit section *** (Заказы CustomMembers)

        
        /// <summary>
        /// ДатаИВремя.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ДатаИВремя CustomAttributes)

        // *** End programmer edit section *** (Заказы.ДатаИВремя CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаИВремя
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ДатаИВремя Get start)

                // *** End programmer edit section *** (Заказы.ДатаИВремя Get start)
                string result = this.fДатаИВремя;
                // *** Start programmer edit section *** (Заказы.ДатаИВремя Get end)

                // *** End programmer edit section *** (Заказы.ДатаИВремя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ДатаИВремя Set start)

                // *** End programmer edit section *** (Заказы.ДатаИВремя Set start)
                this.fДатаИВремя = value;
                // *** Start programmer edit section *** (Заказы.ДатаИВремя Set end)

                // *** End programmer edit section *** (Заказы.ДатаИВремя Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// ТипВручения.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ТипВручения CustomAttributes)

        // *** End programmer edit section *** (Заказы.ТипВручения CustomAttributes)
        public virtual IIS.Serezha.ТипВручения ТипВручения
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ТипВручения Get start)

                // *** End programmer edit section *** (Заказы.ТипВручения Get start)
                IIS.Serezha.ТипВручения result = this.fТипВручения;
                // *** Start programmer edit section *** (Заказы.ТипВручения Get end)

                // *** End programmer edit section *** (Заказы.ТипВручения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ТипВручения Set start)

                // *** End programmer edit section *** (Заказы.ТипВручения Set start)
                this.fТипВручения = value;
                // *** Start programmer edit section *** (Заказы.ТипВручения Set end)

                // *** End programmer edit section *** (Заказы.ТипВручения Set end)
            }
        }
        
        /// <summary>
        /// ТипОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.ТипОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказы.ТипОплаты CustomAttributes)
        public virtual IIS.Serezha.ТипОплаты ТипОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.ТипОплаты Get start)

                // *** End programmer edit section *** (Заказы.ТипОплаты Get start)
                IIS.Serezha.ТипОплаты result = this.fТипОплаты;
                // *** Start programmer edit section *** (Заказы.ТипОплаты Get end)

                // *** End programmer edit section *** (Заказы.ТипОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.ТипОплаты Set start)

                // *** End programmer edit section *** (Заказы.ТипОплаты Set start)
                this.fТипОплаты = value;
                // *** Start programmer edit section *** (Заказы.ТипОплаты Set end)

                // *** End programmer edit section *** (Заказы.ТипОплаты Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Клиенты CustomAttributes)

        // *** End programmer edit section *** (Заказы.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Serezha.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Клиенты Get start)

                // *** End programmer edit section *** (Заказы.Клиенты Get start)
                IIS.Serezha.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (Заказы.Клиенты Get end)

                // *** End programmer edit section *** (Заказы.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Клиенты Set start)

                // *** End programmer edit section *** (Заказы.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (Заказы.Клиенты Set end)

                // *** End programmer edit section *** (Заказы.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Номера CustomAttributes)

        // *** End programmer edit section *** (Заказы.Номера CustomAttributes)
        [PropertyStorage(new string[] {
                "Номера"})]
        [NotNull()]
        public virtual IIS.Serezha.Номера Номера
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Номера Get start)

                // *** End programmer edit section *** (Заказы.Номера Get start)
                IIS.Serezha.Номера result = this.fНомера;
                // *** Start programmer edit section *** (Заказы.Номера Get end)

                // *** End programmer edit section *** (Заказы.Номера Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Номера Set start)

                // *** End programmer edit section *** (Заказы.Номера Set start)
                this.fНомера = value;
                // *** Start programmer edit section *** (Заказы.Номера Set end)

                // *** End programmer edit section *** (Заказы.Номера Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказы.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Serezha.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Сотрудник Get start)

                // *** End programmer edit section *** (Заказы.Сотрудник Get start)
                IIS.Serezha.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказы.Сотрудник Get end)

                // *** End programmer edit section *** (Заказы.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Сотрудник Set start)

                // *** End programmer edit section *** (Заказы.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказы.Сотрудник Set end)

                // *** End programmer edit section *** (Заказы.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.СоставЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.СоставЗаказа CustomAttributes)
        public virtual IIS.Serezha.DetailArrayOfСоставЗаказа СоставЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Get start)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Get start)
                if ((this.fСоставЗаказа == null))
                {
                    this.fСоставЗаказа = new IIS.Serezha.DetailArrayOfСоставЗаказа(this);
                }
                IIS.Serezha.DetailArrayOfСоставЗаказа result = this.fСоставЗаказа;
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Get end)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Set start)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Set start)
                this.fСоставЗаказа = value;
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Set end)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыE", typeof(IIS.Serezha.Заказы));
                }
            }
            
            /// <summary>
            /// "ЗаказыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыL", typeof(IIS.Serezha.Заказы));
                }
            }
        }
    }
}
