//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав заказа.
    /// </summary>
    // *** Start programmer edit section *** (СоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (СоставЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Состав заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставЗаказаE", new string[] {
            "Сумма as \'Сумма\'",
            "Комментарий as \'Комментарий\'",
            "Напитки as \'Напитки\'",
            "Напитки.Наименование as \'Наименование напитка\'",
            "Блюда as \'Блюда\'",
            "Блюда.Наименование as \'Наименование блюда\'"}, Hidden=new string[] {
            "Напитки.Наименование",
            "Блюда.Наименование"})]
    [MasterViewDefineAttribute("СоставЗаказаE", "Напитки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СоставЗаказаE", "Блюда", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private double fСумма;
        
        private string fКомментарий;
        
        private IIS.Serezha.Напитки fНапитки;
        
        private IIS.Serezha.Блюда fБлюда;
        
        private IIS.Serezha.Заказы fЗаказы;
        
        // *** Start programmer edit section *** (СоставЗаказа CustomMembers)

        // *** End programmer edit section *** (СоставЗаказа CustomMembers)

        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Комментарий CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Комментарий Get start)

                // *** End programmer edit section *** (СоставЗаказа.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (СоставЗаказа.Комментарий Get end)

                // *** End programmer edit section *** (СоставЗаказа.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Комментарий Set start)

                // *** End programmer edit section *** (СоставЗаказа.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (СоставЗаказа.Комментарий Set end)

                // *** End programmer edit section *** (СоставЗаказа.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Сумма CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Get start)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Get end)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Set start)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (СоставЗаказа.Сумма Set end)

                // *** End programmer edit section *** (СоставЗаказа.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Состав заказа.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Блюда CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Блюда CustomAttributes)
        [PropertyStorage(new string[] {
                "Блюда"})]
        [NotNull()]
        public virtual IIS.Serezha.Блюда Блюда
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Блюда Get start)

                // *** End programmer edit section *** (СоставЗаказа.Блюда Get start)
                IIS.Serezha.Блюда result = this.fБлюда;
                // *** Start programmer edit section *** (СоставЗаказа.Блюда Get end)

                // *** End programmer edit section *** (СоставЗаказа.Блюда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Блюда Set start)

                // *** End programmer edit section *** (СоставЗаказа.Блюда Set start)
                this.fБлюда = value;
                // *** Start programmer edit section *** (СоставЗаказа.Блюда Set end)

                // *** End programmer edit section *** (СоставЗаказа.Блюда Set end)
            }
        }
        
        /// <summary>
        /// Состав заказа.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Напитки CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Напитки CustomAttributes)
        [PropertyStorage(new string[] {
                "Напитки"})]
        [NotNull()]
        public virtual IIS.Serezha.Напитки Напитки
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Напитки Get start)

                // *** End programmer edit section *** (СоставЗаказа.Напитки Get start)
                IIS.Serezha.Напитки result = this.fНапитки;
                // *** Start programmer edit section *** (СоставЗаказа.Напитки Get end)

                // *** End programmer edit section *** (СоставЗаказа.Напитки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Напитки Set start)

                // *** End programmer edit section *** (СоставЗаказа.Напитки Set start)
                this.fНапитки = value;
                // *** Start programmer edit section *** (СоставЗаказа.Напитки Set end)

                // *** End programmer edit section *** (СоставЗаказа.Напитки Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Serezha.Заказы.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Заказы CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Заказы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказы"})]
        public virtual IIS.Serezha.Заказы Заказы
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказы Get start)

                // *** End programmer edit section *** (СоставЗаказа.Заказы Get start)
                IIS.Serezha.Заказы result = this.fЗаказы;
                // *** Start programmer edit section *** (СоставЗаказа.Заказы Get end)

                // *** End programmer edit section *** (СоставЗаказа.Заказы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказы Set start)

                // *** End programmer edit section *** (СоставЗаказа.Заказы Set start)
                this.fЗаказы = value;
                // *** Start programmer edit section *** (СоставЗаказа.Заказы Set end)

                // *** End programmer edit section *** (СоставЗаказа.Заказы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставЗаказаE", typeof(IIS.Serezha.СоставЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)
    public class DetailArrayOfСоставЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Serezha.DetailArrayOfСоставЗаказа members)

        // *** End programmer edit section *** (IIS.Serezha.DetailArrayOfСоставЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставЗаказа.
        /// </summary>
        public DetailArrayOfСоставЗаказа(IIS.Serezha.Заказы fЗаказы) : 
                base(typeof(СоставЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказы)))
        {
        }
        
        public IIS.Serezha.СоставЗаказа this[int index]
        {
            get
            {
                return ((IIS.Serezha.СоставЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Serezha.СоставЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
