//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип номера.
    /// </summary>
    // *** Start programmer edit section *** (ТипНомера CustomAttributes)

    // *** End programmer edit section *** (ТипНомера CustomAttributes)
    public enum ТипНомера
    {
        
        // *** Start programmer edit section *** (ТипНомера.1 CustomAttributes)

        // *** End programmer edit section *** (ТипНомера.1 CustomAttributes)
        [Caption("Эконом")]
        1,
        
        // *** Start programmer edit section *** (ТипНомера.2 CustomAttributes)

        // *** End programmer edit section *** (ТипНомера.2 CustomAttributes)
        [Caption("Комфорт")]
        2,
        
        // *** Start programmer edit section *** (ТипНомера.3 CustomAttributes)

        // *** End programmer edit section *** (ТипНомера.3 CustomAttributes)
        [Caption("Бизнес")]
        3,
        
        // *** Start programmer edit section *** (ТипНомера.4 CustomAttributes)

        // *** End programmer edit section *** (ТипНомера.4 CustomAttributes)
        [Caption("Президентский")]
        4,
    }
}
