//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип вручения.
    /// </summary>
    // *** Start programmer edit section *** (ТипВручения CustomAttributes)

    // *** End programmer edit section *** (ТипВручения CustomAttributes)
    public enum ТипВручения
    {
        
        // *** Start programmer edit section *** (ТипВручения.1 CustomAttributes)

        // *** End programmer edit section *** (ТипВручения.1 CustomAttributes)
        [Caption("Доставка в номер")]
        1,
        
        // *** Start programmer edit section *** (ТипВручения.2 CustomAttributes)

        // *** End programmer edit section *** (ТипВручения.2 CustomAttributes)
        [Caption("В ресторане")]
        2,
        
        // *** Start programmer edit section *** (ТипВручения.3 CustomAttributes)

        // *** End programmer edit section *** (ТипВручения.3 CustomAttributes)
        [Caption("Навынос")]
        3,
    }
}
